[project]
name = "aoc2024"
version = "0.1.0"
description = "AoC 2024 Project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.0",
    "sympy>=1.13.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pyparsing>=3.2.0",
]
